#define Stick_i &Stick[i*ParamsNum]
#define Stick_1 &Stick[1*ParamsNum]
#define Stick_j &Stick[j*ParamsNum]
#define Stick_2 &Stick[2*ParamsNum]
#define Site_i &Site[i*ParamsNum]
#define Site_j &Site[j*ParamsNum]

#define O2Od_i_j O2Od[i*ObjectNum+j]
#define O2Od_j_i O2Od[j*ObjectNum+i]

#define x Stick[X]
#define y Stick[Y]
#define z Stick[Z]
#define L Stick[Length]
#define W Stick[Width]
#define Th Stick[Theta]
#define F Stick[Fi]
#define x0 Point[X]
#define y0 Point[Y]
#define z0 Point[Z]
#define W0 Point[Width]

#define x1 Stick1[X]
#define y1 Stick1[Y]
#define z1 Stick1[Z]
#define L1 Stick1[Length]
#define W1 Stick1[Width]
#define Th1 Stick1[Theta]
#define F1 Stick1[Fi]
#define E1 Stick1[Energy]
#define x2 Stick2[X]
#define y2 Stick2[Y]
#define z2 Stick2[Z]
#define L2 Stick2[Length]
#define W2 Stick2[Width]
#define Th2 Stick2[Theta]
#define F2 Stick2[Fi]
#define E2 Stick2[Energy]
